routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

\Illuminate\Support\Facades\Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('package', [\App\Http\Controllers\PackageController::class, 'index'])->name('package');
Route::get('package/{package}', [\App\Http\Controllers\PackageController::class, 'show'])->name('package.single');
Route::post('package/{package}/discount', [\App\Http\Controllers\PackageController::class, 'calculateTotalPrice'])->name('package.total');



Route::name('admin.')->middleware(['auth', 'admin.auth'])->prefix('admin')->group(function () {
    Route::get('/', [\App\Http\Controllers\Admin\IndexController::class, 'index'])->name('index');

    Route::get('/packages', [\App\Http\Controllers\Admin\PackagesController::class, 'index'])->name('packages.index');
    Route::get('/packages/create', [\App\Http\Controllers\Admin\PackagesController::class, 'create'])->name('packages.create');
    Route::post('/packages/create', [\App\Http\Controllers\Admin\PackagesController::class, 'store'])->name('packages.store');


    Route::get('/discounts', [\App\Http\Controllers\Admin\DiscountsController::class, 'index'])->name('discounts.index');
    Route::get('/discounts/create', [\App\Http\Controllers\Admin\DiscountsController::class, 'create'])->name('discounts.create');
    Route::post('/discounts/create', [\App\Http\Controllers\Admin\DiscountsController::class, 'store'])->name('discounts.store');
    Route::get('/discounts/{discount}/edit', [\App\Http\Controllers\Admin\DiscountsController::class, 'edit'])->name('discounts.edit');
    Route::put('/discounts/{discount}/edit', [\App\Http\Controllers\Admin\DiscountsController::class, 'update'])->name('discounts.update');
    Route::delete('/discounts/{discount}/delete', [\App\Http\Controllers\Admin\DiscountsController::class, 'destroy'])->name('discounts.delete');
    Route::delete('/discounts/single/{id}/delete', [\App\Http\Controllers\Admin\DiscountsController::class, 'singleDestroy'])->name('discounts.single.delete');
});


Route::get('test', function () {
    return \App\Models\DiscountCode::generateCode();
});

app/Models/Discount.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Discount extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'start_time',
        'end_time',
        'first_purchase',
        'usable_count',
        'percent_off',
        'is_ready'
    ];

    public static function validateDiscountCode($code, $package)
    {
        $package = Package::whereId($package)->first();

        $discountIDs = [];
        foreach ($package->discounts as $key => $discounts) {
            $discountIDs[] = $discounts->pivot->discount_id;
        }

        $checkHasDiscountCode = DiscountCode::whereIn('discount_id', $discountIDs)
                                            ->whereCode($code)
                                            ->where('is_used', 0)
                                            ->first();

        if ( ! $checkHasDiscountCode) {
            return false;
        }

        return true;

    }

    public static function calculateDiscount($package, $code)
    {
        $discountIDs = [];
        foreach ($package->discounts as $key => $discounts) {
            $discountIDs[] = $discounts->pivot->discount_id;
        }

        $getCode = DiscountCode::whereIn('discount_id', $discountIDs)
                            ->whereCode($code)
                            ->first();

        $percent = $getCode->discount->percent_off;

        $totalPrice = ( $package->price * $percent ) / 100;

        return $totalPrice;
    }

    public function discountDiffTime()
    {
        $now  = Carbon::now();
        $end  = $this->end_time;
        $daysLeft = $now->diffInDays($end);

        return $daysLeft;
    }



    // Relations
    public function codes()
    {
        return $this->hasMany(DiscountCode::class);
    }

    public function packages()
    {
        return $this->belongsToMany(Package::class, 'discount_package', 'discount_id', 'package_id');
    }
}

app/Http/Controllers/Admin/DiscountsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Jobs\DiscountsJob;
use App\Models\Discount;
use App\Models\DiscountCode;
use App\Models\Package;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\LazyCollection;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

class DiscountsController extends Controller
{
    public function index()
    {
        $discounts = Discount::orderBy('id', 'DESC')
                            ->paginate(3);
        return view('admin.discount.index', compact('discounts'));
    }

    public function create()
    {
        return view('admin.discount.create', [
            'packages' => Package::all()
        ]);
    }

    public function store(Request $request)
    {
        $validData = $request->validate([
            'title' => 'required|unique:discounts,title',
            'start_time' => 'required',
            'end_time' => 'required',
            'usable_count' => 'required',
            'first_purchase' => 'required',
            'packages' => 'required',
            'create_number' => 'required',
        ]);
//        return DiscountCode::generateCode(3);
        $discount = Discount::create([
            'title' => $request->title,
            'start_time' => $request->start_time,
            'end_time' => $request->end_time,
            'usable_count' => $request->usable_count,
            'first_purchase' => $request->first_purchase,
            'percent_off' => $request->percent_off,
        ]);

        $discount->packages()->attach($request->packages);

        DiscountsJob::dispatch($discount, $request->create_number);

        return back()->with('success', 'Discount successfully added. Please wait to create Codes.');
    }

    public function edit(Discount $discount)
    {
        return view('admin.discount.edit', compact('discount'));
    }

    public function update(Discount $discount, Request $request)
    {
        $validData = $request->validate([
            'start_time' => 'required',
            'end_time' => 'required',
            'usable_count' => 'required',
            'first_purchase' => 'required',
        ]);

        $discount->update([
            'start_time' => $request->start_time,
            'end_time' => $request->end_time,
            'first_purchase' => $request->first_purchase,
            'usable_count' => $request->usable_count,
        ]);

        return back()->with('success', 'Discount successfully updated.');
    }

    public function destroy(Discount $discount)
    {
        $discount->delete();
        return back()->with('success', 'Discount successfully deleted.');
    }

    public function singleDestroy($id)
    {
        DiscountCode::find($id)->delete();
        return back()->with('success', 'Discount successfully deleted.');
    }
}

resources/views/admin/discount/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">

                    <div class="card-header">Create Discount</div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger">
                                {{ session('error') }}
                            </div>
                        @endif

                        <form action="{{route('admin.discounts.store')}}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label>Title:</label>
                                <input type="text" class="form-control" name="title" placeholder="Say Smthng" value="{{old('title')}}">
                            </div>

                            <div class="form-group">
                                <label>Start Time:</label>
                                <input type="datetime-local" class="form-control" name="start_time" value="{{old('start_time')}}">
                            </div>

                            <div class="form-group">
                                <label>End Time:</label>
                                <input type="datetime-local" class="form-control" name="end_time" value="{{old('end_time')}}">
                            </div>

                            <div class="form-group">
                                <label>Usable Count:</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="usable_count" id="exampleRadios1" value="1">
                                    <label class="form-check-label" for="exampleRadios1">
                                        One Person
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="usable_count" id="exampleRadios1" value="99999999999999">
                                    <label class="form-check-label" for="exampleRadios1">
                                        Many Person
                                    </label>
                                </div>
                            </div>


                            <div class="form-group">
                                <label>First Purchase:</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="first_purchase" id="exampleRadios1" value="1">
                                    <label class="form-check-label" for="exampleRadios1">
                                        True
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="first_purchase" id="exampleRadios1" value="0">
                                    <label class="form-check-label" for="exampleRadios1">
                                        False
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Package:</label>
                                <select multiple class="form-control" name="packages[]">
                                    @foreach($packages as $package)
                                        <option value="{{$package->id}}">{{$package->title}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <label>Number of discount code:</label>
                                <input type="number" class="form-control" name="create_number" value="{{old('create_number')}}">
                            </div>

                            <div class="form-group">
                                <label>Percent off:</label>
                                <input type="number" class="form-control" name="percent_off" value="{{old('percent_off')}}">
                            </div>

                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/discount/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">

                    <div class="card-header">Edit {{$discount->title}}</div>

                    <div class="card-body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        @if (session('success'))
                            <div class="alert alert-success">
                                {{ session('success') }}
                            </div>
                        @endif

                        <form action="{{route('admin.discounts.update', $discount)}}" method="POST">
                            @csrf
                            @method('put')
                            <div class="form-group">
                                <label>Start Time:</label>
                                <input type="datetime-local" class="form-control" name="start_time" value="{{$discount->start_time}}">
                            </div>

                            <div class="form-group">
                                <label>End Time:</label>
                                <input type="datetime-local" class="form-control" name="end_time" value="{{$discount->end_time}}">
                            </div>

                            <div class="form-group">
                                <label>Usable Count:</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="usable_count" id="exampleRadios1" value="1" {{$discount->usable_count == 1 ? 'checked' : ''}}>
                                    <label class="form-check-label" for="exampleRadios1">
                                        One Person
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="usable_count" id="exampleRadios1" value="99999999999999" {{$discount->usable_count == 99999999999999 ? 'checked' : ''}}>
                                    <label class="form-check-label" for="exampleRadios1">
                                        Many Person
                                    </label>
                                </div>
                            </div>


                            <div class="form-group">
                                <label>First Purchase:</label>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="first_purchase" id="exampleRadios1" value="1" {{$discount->first_purchase == 1 ? 'checked' : ''}}>
                                    <label class="form-check-label" for="exampleRadios1">
                                        True
                                    </label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" type="radio" name="first_purchase" id="exampleRadios1" value="0" {{$discount->first_purchase == 0 ? 'checked' : ''}}>
                                    <label class="form-check-label" for="exampleRadios1">
                                        False
                                    </label>
                                </div>
                            </div>

                            <button type="submit" class="btn btn-primary">Submit</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/discount/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="d-flex justify-content-between mb-5">
                    <h3>Discounts list</h3>
                    <a href="{{route('admin.discounts.create')}}" class="btn btn-primary">+ Create new</a>
                </div>
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Start Time</th>
                            <th>End Time</th>
                            <th>Codes</th>
                            <th>Usable Counts</th>
                            <th>First Purchase</th>
                            <th>Created At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($discounts as $discount)
                            <tr>
                                <td>{{$discount->id}}</td>
                                <td>{{$discount->title}}</td>
                                <td>{{$discount->start_time}}</td>
                                <td>{{$discount->end_time}}</td>
                                <td>
                                    @if (! $discount->is_ready)
                                        <span class="badge badge-sm badge-warning">is loading...</span>
                                    @else
                                        <button type="button" class="btn btn-sm btn-primary" data-toggle="modal" data-target="#exampleModal{{$discount->id}}">
                                            {{count($discount->codes)}} Codes
                                        </button>
                                        <!-- Modal -->
                                        <div class="modal fade" id="exampleModal{{$discount->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="modal-dialog" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLabel">Codes</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        @foreach($discount->codes as $code)
                                                            <ul class="list-group">
                                                                <li class="list-group-item">
                                                                    <div class="d-flex justify-content-between">
                                                                        <span>Code: {{$code->code}}</span>
                                                                        <form action="{{route('admin.discounts.single.delete', $code->id)}}" method="post">
                                                                            @csrf
                                                                            @method('DELETE')
                                                                            <button class="btn btn-danger btn-sm ml-1" type="submit">Delete</button>
                                                                        </form>
                                                                    </div>
                                                                </li>
                                                            </ul>
                                                        @endforeach
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                        <button type="button" class="btn btn-primary">Save changes</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endif
                                </td>
                                <td>{{$discount->usable_counts == 1 ? '1 Person' : 'Many Person' }}</td>
                                <td>{{$discount->first_purchase ? 'True' : 'False'}}</td>
                                <td>{{$discount->created_at}}</td>
                                <td class="d-flex justify-content-start">
                                    <a href="{{route('admin.discounts.edit', $discount)}}" class="btn btn-sm btn-primary">Edit</a>
                                    <form action="{{route('admin.discounts.delete', $discount)}}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-sm ml-1" type="submit">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection